name: Test Github Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Databricks Repo Update
      run: |
        curl --location --request PATCH 'https://dbc-6fe6e0d2-1c0d.cloud.databricks.com/api/2.0/repos/1642747384591653' \
          --header 'Authorization: Bearer ${{ secrets.DB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"branch": "master"}'
          
    - name: Test CMD
      run: |
        echo "This is a test"
        
    - name: Sleep 10 Sec
      run: |
        sleep 10
